const fs = require('node:fs');
const path = require('node:path');
const copy = require('../site-copy');
const {ROOT, ORIGIN, LANGUAGES, ROUTES, escape:e, route, publicPath, readContent, paragraphs} = require('./site-lib');
const portrait='Fotos.img/IMG_20240831_132753.jpg',cover='Fotos.img/yasama-dair.jpg',email='sisiyi889900@gmail.com';
const socials=[['YouTube','https://www.youtube.com/@huseyinemil35'],['Instagram','https://www.instagram.com/huseyinemil35'],['Facebook','https://www.facebook.com/huseyin.emil.3']];
const icon=name=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${({arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',play:'<path d="m9 5 11 7-11 7z" fill="currentColor" stroke="none"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',rss:'<circle cx="6" cy="18" r="1"/><path d="M5 11a8 8 0 0 1 8 8M5 5a14 14 0 0 1 14 14"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',expand:'<path d="M14 4h6v6M10 20H4v-6M20 4l-7 7M4 20l7-7"/>'})[name]}</svg>`;
const link=(url,text,cls='text-link',external=false)=>`<a class="${cls}" href="${e(url)}"${external?' target="_blank" rel="noopener noreferrer"':''}>${e(text)}${icon('arrow')}</a>`;
const image=(src,alt,cls='',eager=false)=>`<img class="${cls}" src="${e(src)}" alt="${e(alt)}" width="${src===portrait?2448:1280}" height="${src===portrait?3264:720}" loading="${eager?'eager':'lazy'}" decoding="async"${eager?' fetchpriority="high"':''}>`;
const date=(value,lang)=>value?new Intl.DateTimeFormat(copy[lang].locale,{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)):'';
const meta=(value,lang)=>value?`<time datetime="${e(value)}">${e(date(value,lang))}</time>`:'';
const reading=item=>Math.max(1,Math.ceil(paragraphs(item).join(' ').split(/\s+/).length/180));
const excerpt=item=>{const text=paragraphs(item).join(' ');return text.length>200?text.slice(0,197).replace(/\s+\S*$/,'')+'…':text;};
const pageUrl=(page,lang)=>`${ORIGIN}/${page==='index'&&lang==='tr'?'':route(page,lang)}`;
function header(page,lang){const t=copy[lang];return `<a class="skip-link" href="#main">${t.skip}</a><header class="site-header" id="top"><div class="masthead wrap"><a class="brand" href="${route('index',lang)}" aria-label="Yaşama Dair — ${t.nav[0]}">yaşama dair<span>.</span></a><p class="journal-name">${t.journal}</p><div class="header-actions"><div class="languages" role="group" aria-label="${t.languages}">${LANGUAGES.map(l=>`<a href="${route(page,l)}" lang="${l}" hreflang="${l}" aria-label="${copy[l].language}"${l===lang?' aria-current="true"':''}>${l.toUpperCase()}</a>`).join('')}</div><button class="menu-toggle" type="button" aria-controls="site-navigation" aria-expanded="false">${icon('menu')}<span>${t.menu}</span></button></div></div><div class="navigation-shell"><nav class="site-navigation wrap" id="site-navigation" aria-label="${t.footerMenu}">${ROUTES.slice(0,8).map((p,i)=>`<a href="${route(p,lang)}"${p===page?' aria-current="page"':''}>${t.nav[i]}</a>`).join('')}</nav></div></header>`;}
function footer(lang){const t=copy[lang];return `<footer class="site-footer"><div class="wrap footer-top"><div class="footer-intro"><a class="brand" href="${route('index',lang)}">yaşama dair<span>.</span></a><p>${t.footerText}</p><span class="signature">Hüseyin Emil</span></div><div><h2 class="eyebrow">${t.footerMenu}</h2><ul class="footer-links">${ROUTES.slice(1,8).map((p,i)=>`<li><a href="${route(p,lang)}">${t.nav[i+1]}</a></li>`).join('')}</ul></div><div><h2 class="eyebrow">${t.footerFollow}</h2><ul class="footer-links">${socials.map(([n,u])=>`<li><a href="${u}" target="_blank" rel="noopener noreferrer">${n}</a></li>`).join('')}<li><a href="feed.xml">Podcast RSS</a></li><li><a href="mailto:${email}">${t.emailLabel}</a></li></ul></div></div><div class="wrap footer-bottom"><p>© 2026 ${t.copyright}</p><a href="#top">${t.top} ↑</a></div></footer>`;}
function heading(tag,title,url,action){return `<div class="section-heading"><div><p class="eyebrow">${e(tag)}</p><h2>${e(title)}</h2></div>${url?link(url,action):''}</div>`;}
function podcast(p,index,lang,media,featured=false){const t=copy[lang],info=media[p.audio],id=featured?'featured-audio':`episode-audio-${index}`,number=/\d+/.exec(p.tag||'')?.[0]||String(index+1).padStart(2,'0');return `<article class="podcast-card ${featured?'podcast-featured':''}"${featured?' id="featured-podcast"':''}><div class="podcast-art">${image(p.cover||cover,p.title)}<span class="episode-number">${number}</span></div><div class="podcast-body"><div class="eyebrow episode-meta"><span>${e(featured?t.latest:p.tag)}</span><span>${info?`${Math.ceil(info.duration/60)} ${t.duration}`:''}</span></div><h${featured?2:3}>${e(p.title)}</h${featured?2:3}><p class="podcast-description">${e(p.description)}</p><div class="metadata">${meta(p.date,lang)}<span>${t.audioLanguage}</span></div><audio id="${id}" controls preload="none" aria-label="${e(p.title)}"><source src="${e(p.audio)}" type="audio/mpeg">${t.audioFallback}</audio><div class="audio-foot">${link(p.audio,t.audioFallback,'quiet-link')}<span class="media-status" role="status" aria-live="polite"></span></div>${!featured&&p.notes?`<details class="episode-notes"><summary>${({tr:'Bölüm notları',de:'Notizen zur Folge',en:'Episode notes'})[lang]}</summary><p>${e(p.notes)}</p>${link(route('felsefe',lang),t.allThoughts)}</details>`:''}</div></article>`;}
function thoughtCards(data,lang){const t=copy[lang];return `<div class="thought-grid">${data.philosophy.map((p,i)=>({p,i})).sort((a,b)=>b.p.date.localeCompare(a.p.date)).slice(0,3).map(({p,i},n)=>`<article class="thought-card"><div class="thought-top"><span class="article-number">0${n+1}</span><span class="metadata">${reading(p)} ${t.reading}</span></div><h3><a href="${route('felsefe',lang)}#yazi-${i+1}">${e(p.title)}</a></h3><p>${e(excerpt(p))}</p>${link(`${route('felsefe',lang)}#yazi-${i+1}`,t.readMore)}</article>`).join('')}</div>`;}
function commentForm(page,lang){const t=copy[lang],name=({tr:'yorumlar',en:'comments',de:'comments-de'})[lang];return `<section class="comment-section section wrap" id="comments"><div class="comment-intro"><p class="eyebrow">${t.nav[7]}</p><h2>${t.commentTitle}</h2><p>${t.commentText}</p><p class="small-text">${t.privateContact}</p>${link(`mailto:${email}`,t.emailLabel)}</div><form class="comment-form" name="${name}" method="POST" action="/${route('tesekkurler',lang)}" data-netlify="true" netlify-honeypot="bot-field"><input type="hidden" name="form-name" value="${name}"><input type="hidden" name="page" value="${route(page,lang)}"><input type="hidden" name="language" value="${lang}"><p class="honeypot" aria-hidden="true"><label>Leave this blank <input name="bot-field" tabindex="-1" autocomplete="off"></label></p><div class="form-grid"><label>${t.name} <span>(${t.optional})</span><input name="name" type="text" autocomplete="name" maxlength="100"></label><label>${t.email} <span>(${t.optional})</span><input name="email" type="email" autocomplete="email" maxlength="254"></label></div><label>${t.message}<textarea name="message" rows="5" required minlength="3" maxlength="5000"></textarea></label><label class="checkbox"><input name="consent" value="yes" type="checkbox" required><span>${t.consent}</span></label><button class="button" type="submit" data-sending="${t.sending}">${t.send}${icon('arrow')}</button><p class="small-text form-note">${t.moderation}</p></form></section>`;}
function comments(data,lang){const t=copy[lang],list=data.comments||[];if(!list.length)return '';return `<section class="reader-section section wrap"><p class="eyebrow">${t.commentHeading}</p><div class="reader-comments">${list.map((c,i)=>`<article class="reader-comment"${i>4?' data-extra-comment hidden':''}><header><span class="reader-avatar" aria-hidden="true">${e((c.name||t.visitor).slice(0,1))}</span><div><h3>${e(c.name||t.visitor)}</h3><div class="metadata">${meta(c.date,lang)}</div></div></header><p>${e(c.message)}</p>${c.reply?`<div class="reader-reply"><span class="eyebrow">${t.reply}</span><p>${e(c.reply)}</p></div>`:''}</article>`).join('')}</div>${list.length>5?`<button class="button button-outline" type="button" data-more-comments>${t.moreComments}</button>`:''}</section>`;}
function home(data,lang,media){const t=copy[lang],newest=[...data.podcasts].sort((a,b)=>b.date.localeCompare(a.date))[0];return `<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">${t.storyTag}</p><h1>${t.hero[0]}<br>${t.hero[1]}<br><em>${t.hero[2]}</em></h1><p class="hero-description">${t.intro}</p><div class="hero-actions">${link(newest?'#featured-podcast':route('podcast',lang),t.listen,'button')}${link(route('felsefe',lang),t.read)}</div><div class="hero-byline"><span class="byline-rule"></span><span>${t.author}<small>${t.authorNote}</small></span></div></div><figure class="hero-portrait">${image(portrait,t.portrait,'',true)}<figcaption><span>YAŞAMA DAİR</span><span>01 / ${t.nav[1]}</span></figcaption></figure></section><div class="topics-strip"><div class="wrap">${['felsefe','podcast','fotograflar','videolar'].map((p,i)=>`<a href="${route(p,lang)}"><span class="topic-index">0${i+1}</span>${t.nav[ROUTES.indexOf(p)]}${icon('arrow')}</a>`).join('')}</div></div><section class="section wrap">${heading('PODCAST',t.titles.podcast,route('podcast',lang),t.allEpisodes)}${newest?podcast(newest,0,lang,media,true):`<p>${t.noItems}</p>`}</section><section class="section wrap thoughts-section">${heading(t.thoughts,t.thoughtsIntro,route('felsefe',lang),t.allThoughts)}${thoughtCards(data,lang)}</section><section class="story-band"><div class="wrap story-band-inner"><p class="eyebrow">${t.storyTag}</p><h2>${t.storyTitle}</h2><div><p>${t.storyText}</p>${link(route('hikayem',lang),t.storyMore)}</div></div></section><section class="section wrap explore-section">${heading('YAŞAMA DAİR',t.explore)}<div class="explore-grid"><a class="explore-link" href="${route('fotograflar',lang)}"><span class="eyebrow">${t.nav[4]}</span><h3>${t.explorePhoto}</h3><p>${t.explorePhotoText}</p>${icon('arrow')}</a><a class="explore-link" href="${route('videolar',lang)}"><span class="eyebrow">${t.nav[5]}</span><h3>${t.exploreVideo}</h3><p>${t.exploreVideoText}</p>${icon('arrow')}</a></div></section>${data.news.length?`<section class="news-brief wrap"><p class="eyebrow">${t.nav[6]}</p><div><h2>${e(data.news[0].title)}</h2><p>${e(data.news[0].text)}</p></div>${link(route('haberler',lang),t.nav[6])}</section>`:''}${comments(data,lang)}${commentForm('index',lang)}`;}
function pageHeading(page,lang){const t=copy[lang];return `<header class="page-heading wrap"><div class="breadcrumb"><a href="${route('index',lang)}">${t.nav[0]}</a><span aria-hidden="true">/</span><span>${t.nav[ROUTES.indexOf(page)]||t.titles[page]}</span></div><p class="eyebrow">YAŞAMA DAİR · ${t.author}</p><h1>${t.titles[page]}</h1><p>${t.descriptions[page]}</p></header>`;}
function videos(lang){const t=copy[lang];return `<div class="video-grid">${['OfJ9THLFNTw','HAxEmDM5mjQ','NKrfUHwPNJs'].map((id,i)=>`<article class="video-card"><div class="video-facade"><button class="youtube-load" type="button" data-youtube="${id}" aria-label="${t.videoPlay} ${i+1}" hidden>${icon('play')}<span>YouTube</span></button><noscript><a class="video-noscript" href="https://www.youtube.com/watch?v=${id}">${t.videoExternal}</a></noscript><span class="video-index" aria-hidden="true">0${i+1}</span></div><div class="video-caption"><h2>${i===2?t.shortLabel:t.videoLabel} ${String(i+1).padStart(2,'0')}</h2>${link(`https://www.youtube.com/watch?v=${id}`,t.videoExternal,'quiet-link',true)}</div><p class="small-text">${t.videoNotice}</p></article>`).join('')}<article class="video-card"><div class="local-video"><video controls preload="none" poster="${cover}" aria-label="${t.videoLocal}"><source src="video/turkiye-politik-korku.mp4" type="video/mp4"><a href="video/turkiye-politik-korku.mp4">${t.videoFallback}</a></video></div><div class="video-caption"><h2>${t.videoLocal}</h2></div><p>${t.videoLocalDesc}</p>${link('video/turkiye-politik-korku.mp4',t.videoFallback,'quiet-link')}</article></div>`;}
function body(page,data,lang,media){const t=copy[lang];if(page==='index')return home(data,lang,media);let section='';
if(page==='hikayem')section=`<section class="story-page wrap section"><figure>${image(portrait,t.portrait,'',true)}<figcaption>${t.author}</figcaption></figure><div class="story-prose"><h2>${t.storyTitle}</h2><p class="lead">${t.storyText}</p>${t.storyParagraphs.map(p=>`<p>${p}</p>`).join('')}<blockquote>${t.quote}</blockquote><span class="signature">Hüseyin Emil</span>${link(route('podcast',lang),t.listen,'button')}</div></section>`;
if(page==='podcast')section=`<section class="section wrap"><div class="list-heading"><h2>${t.episodes} <span class="count">${data.podcasts.length}</span></h2><a class="text-link" href="feed.xml">${icon('rss')}${t.rss}</a></div><div class="podcast-list">${[...data.podcasts].sort((a,b)=>b.date.localeCompare(a.date)).map((p,i)=>podcast(p,i,lang,media)).join('')||`<p>${t.noItems}</p>`}</div></section>`;
if(page==='felsefe')section=`<section class="writing-layout wrap section"><nav class="writing-index" aria-label="${t.allThoughts}"><p class="eyebrow">${t.thoughts}</p>${data.philosophy.map((p,i)=>`<a href="#yazi-${i+1}"><span>0${i+1}</span>${e(p.title)}</a>`).join('')}</nav><div class="writing-list">${data.philosophy.map((p,i)=>`<article class="writing" id="yazi-${i+1}"><div class="metadata">${meta(p.date,lang)}<span>${reading(p)} ${t.reading}</span></div><h2>${e(p.title)}</h2>${paragraphs(p).map(text=>`<p>${e(text)}</p>`).join('')}<p class="article-author">${t.author}</p></article>`).join('')||`<p>${t.noItems}</p>`}</div></section>`;
if(page==='fotograflar')section=`<section class="section wrap"><div class="photo-gallery">${data.photos.map(p=>`<figure class="photo-figure"><a href="${e(p.image)}" class="photo-open" data-photo="${e(p.image)}" data-caption="${e(p.title)}" aria-label="${t.photoOpen}: ${e(p.title)}">${image(p.image,p.caption||p.title)}<span class="photo-expand">${icon('expand')}${t.photoOpen}</span></a><figcaption><h2>${e(p.title)}</h2><div class="metadata">${meta(p.date,lang)}</div><p>${e(p.caption)}</p></figcaption></figure>`).join('')||`<p>${t.noItems}</p>`}</div></section><dialog class="photo-dialog" aria-label="${t.photoOpen}"><button class="dialog-close" aria-label="${t.close}" type="button" autofocus>${icon('close')}</button><img alt=""><div class="dialog-caption"><p></p><a class="quiet-link">${t.photoOriginal}</a></div></dialog>`;
if(page==='videolar')section=`<section class="section wrap">${videos(lang)}<div class="channel-banner"><div><p class="eyebrow">YOUTUBE</p><h2>${t.exploreVideo}</h2></div>${link(socials[0][1],t.videoChannel,'button',true)}</div></section>`;
if(page==='haberler')section=`<section class="section wrap news-list">${data.news.map(p=>`<article class="news-item"><div class="metadata">${meta(p.date,lang)}</div><div><h2>${e(p.title)}</h2><p>${e(p.text)}</p>${p.link&&/^https?:\/\//.test(p.link)?link(p.link,t.readMore,'text-link',true):link(route('podcast',lang),t.listen)}</div></article>`).join('')||`<p>${t.noItems}</p>`}</section>`;
if(page==='iletisim')section=`<section class="section wrap contact-grid"><article><div class="contact-icon">${icon('mail')}</div><p class="eyebrow">${t.emailLabel}</p><h2><a href="mailto:${email}">${email}</a></h2><p>${t.privateContact}</p></article><article><p class="eyebrow">${t.socialLabel}</p><h2>${t.socialIntro}</h2><div class="social-list">${socials.map(([n,u])=>link(u,n,'text-link',true)).join('')}</div></article></section>${comments(data,lang)}`;
if(page==='tesekkurler')return pageHeading(page,lang)+`<section class="wrap success-section">${link(route('index',lang),t.back,'button')}${link(route('podcast',lang),t.listen)}</section>`;
return pageHeading(page,lang)+section+commentForm(page,lang);}
function document(page,data,lang,media){const t=copy[lang],title=page==='index'?`Yaşama Dair | ${t.journal}`:`${t.titles[page]} | Yaşama Dair`,description=page==='index'?t.intro:t.descriptions[page],url=pageUrl(page,lang);const jsonld=JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:title,description,url,inLanguage:lang,isPartOf:{'@type':'WebSite',name:'Yaşama Dair',url:ORIGIN},author:{'@type':'Person',name:'Hüseyin Emil'}}).replace(/</g,'\\u003c');return `<!DOCTYPE html>\n<html lang="${lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="theme-color" content="#f7f5f0"><link rel="canonical" href="${url}">${LANGUAGES.map(l=>`<link rel="alternate" hreflang="${l}" href="${pageUrl(page,l)}">`).join('')}<link rel="alternate" hreflang="x-default" href="${pageUrl(page,'tr')}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:site_name" content="Yaşama Dair">${page==='podcast'&&lang==='tr'?`<meta property="og:image" content="${ORIGIN}/${cover}">`:''}${page==='tesekkurler'?'<meta name="robots" content="noindex,follow">':''}<link rel="alternate" type="application/rss+xml" title="Yaşama Dair Podcast RSS" href="feed.xml"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script type="application/ld+json">${jsonld}</script><script src="nav.js" defer></script><script src="app.js" defer></script></head><body class="${page==='index'?'home':'inner-page'}" data-page="${page}" data-media-error="${e(t.audioError)}">${header(page,lang)}<main id="main" tabindex="-1">${body(page,data,lang,media)}</main>${footer(lang)}</body></html>\n`;}
async function build(){const {parseFile}=await import('music-metadata');const media={};for(const p of readContent('tr').podcasts){const file=publicPath(p.audio),info=await parseFile(file,{duration:true});media[p.audio]={duration:info.format.duration||0,bytes:fs.statSync(file).size};}for(const lang of LANGUAGES){const data=readContent(lang);for(const page of ROUTES)fs.writeFileSync(path.join(ROOT,route(page,lang)),document(page,data,lang,media).replace(/></g,'>\n<'));}
const notFound=`<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sayfa bulunamadı | Yaşama Dair</title><meta name="robots" content="noindex,follow"><link rel="stylesheet" href="/style.css"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><script src="/nav.js" defer></script></head><body>${header('index','tr')}<main id="main" tabindex="-1"><section class="page-heading wrap"><p class="eyebrow">404 · YAŞAMA DAİR</p><h1>${copy.tr.notFound}</h1><p>${copy.tr.notFoundText}</p></section><section class="wrap success-section">${link('/index.html',copy.tr.back,'button')}${link('/index.de.html','Zur Startseite')}${link('/index.en.html','Back to home')}</section></main>${footer('tr')}</body></html>`;
// A 404 may be served at a nested URL: make all local navigation root-relative.
fs.writeFileSync(path.join(ROOT,'404.html'),notFound.replace(/href="(?!https?:|mailto:|#|\/)([^"]+)"/g,'href="/$1"'));
const dist=path.join(ROOT,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});const publicFiles=fs.readdirSync(ROOT).filter(name=>(/\.html$/.test(name)&&name!=='comments.html')||['style.css','app.js','nav.js','favicon.svg','feed.xml','robots.txt','sitemap.xml'].includes(name));for(const name of publicFiles)fs.copyFileSync(path.join(ROOT,name),path.join(dist,name));for(const name of ['Fotos.img','ses','video','writings'])fs.cpSync(path.join(ROOT,name),path.join(dist,name),{recursive:true});console.log(`Built ${LANGUAGES.length*ROUTES.length} localized pages and public assets in dist/.`);}
build().catch(error=>{console.error(error);process.exitCode=1;});
